### ISSUE TITLE
Serialize OL vector layer to Geojson with simplestyle-spec properties

### ISSUE THREAD

**Issue by shaunakv1** [boundlessgeo/mapbox-to-ol-style#10]
@ahocevar It would be a great addition to support exporting an OL vector layer as GeoJSON with simplestyle-spec compliance that way, an drawing application can implement a full draw-save-import feature. Is there a plan to build this into the library?

**Comment by ahocevar** [comment]
Thanks for your interest @shaunakv1. There is no plan to make this library support that. The dynamic styles (i.e. style functions) created by this library cannot be serialized to simplestyle-spec GeoJSON attributes.

**Comment by shaunakv1** [comment]
@ahocevar thank you for the response. I was just checking to see I don't reinvent the wheel. I have started implementing it as an OL control for one of my project needs. I am not using the style functions though, instead the style options object that OL supports.  As simplestyle-spec is a small subset of the options provided by OL, it seems to work.
