### ISSUE TITLE
Using in AMD environment

### ISSUE THREAD

**Issue by drnextgis** [boundlessgeo/mapbox-to-ol-style#16]
Hello Boundless team.

Big thanks for such amazing library! But I've faced with some problems with it. Now it is impossible to use it within AMD environment because final build contains links to not existed files. I've made couple of changes to solve my problem and want to know what do you think about it: https://github.com/drnextgis/mapbox-to-ol-style/commit/8f332194732bf929cdd98521dd6f992e560d9865 If it is possible to get `ol` object from `olLayer` argument of `mb2olstyle` function then new  `ol` argument can be excluded from signature.

**Comment by ahocevar** [comment]
This library was designed to be used either standalone with a full build of OpenLayers (like shown in the examples), or with a mainstream bundler (Browserify, Webpack etc.) and the [ol package](https://npmjs.com/package/ol) (like shown in the tests).

**Comment by ahocevar** [comment]
@drnextgis Were you able to work things out with the information above?

**Comment by drnextgis** [comment]
@ahocevar thank you for your help. I've modified a source code of mapbox-to-ol style a little bit as mentioned above and it seems that issue can be closed.
