### ISSUE TITLE
Uncaught TypeError: geometry.getInteriorPoint is not a function

### ISSUE THREAD

**Issue by erictheise** [boundlessgeo/mapbox-to-ol-style#18]
@ahocevar, I'm having what seems like a similar issue to what was asked in https://github.com/boundlessgeo/ol-mapbox-style/issues/8 and am hoping you'll have some insights.

I used [imposm3](https://github.com/omniscale/imposm3) to import a Mapzen metro extract and am using [tegola](https://github.com/terranodo/tegola) & [tegola-osm](https://github.com/terranodo/tegola-osm) to serve that data. I can render the full extent of my extract but things break as I zoom in. I can pan around, toggling between the error and a successful render.

**Comment by ahocevar** [comment]
This issue should be fixed in the latest version. Just make sure you are using OpenLayers 4.5 at least, which has getInteriorPoint for ol.render.Feature.

**Comment by erictheise** [comment]
Appreciate the update, @ahocevar, thanks.
