### ISSUE TITLE
support data driven styles 

### ISSUE THREAD

**Issue by brambow** [boundlessgeo/mapbox-to-ol-style#25]
The mapbox style spec has support for data driven styles, such as:

```
        paint: {
          "circle-radius": 3,
          "circle-stroke-color": "white",
          "circle-color": {
            property: "serverPriority",
            stops: [["LPP", "yellow"], ["MPP", "orange"], ["HPP", "red"]]
          }
        },
```

But this project seems to recommend using filters + multiple layers as an alternative.

I mentioned this here, but it's probably more appropriate as an issue on this project.

https://github.com/boundlessgeo/sdk/issues/807

**Comment by ahocevar** [comment]
This is on the roadmap and will be added soon.

**Comment by brambow** [comment]
You know, I was digging through the code of this and taking another look at the mapbox spec, and I believe this already is supported.  I was just missing the 'type' property for 'circle-color' in the example above.

        paint: {
          "circle-radius": 3,
          "circle-stroke-color": "white",
          "circle-color": {
            property: "serverPriority",
            type: "categorical", //added this line
            stops: [["LPP", "yellow"], ["MPP", "orange"], ["HPP", "red"]]
          }
        },

Now it works!

**Comment by ahocevar** [comment]
Thanks for the feedback! Looks like the Mapbox functions parser takes care of this.
